name: vip_tourist
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.5+6

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  rounded_loading_button: ^2.0.5
  auth_buttons: ^1.0.1+4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  persistent_bottom_nav_bar: ^4.0.2
  flutter_rating_bar: ^4.0.0
  octo_image: ^1.0.0+1
  carousel_slider: ^4.0.0
  background_app_bar: ^2.0.0
  timelines: ^0.1.0
  scroll_to_index: ^2.0.0
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  country_calling_code_picker: ^2.0.0
  equatable: ^2.0.3
  firebase_core: ^1.20.0
  formz: ^0.4.0
  flow_builder: ^0.0.3
  provider: ^6.0.1
  form_field_validator: ^1.1.0
  expandable_widgets: ^1.0.2
  adaptive_dialog: ^1.1.0
  http: ^0.13.3
  image_picker: ^0.8.3
  dio: ^4.0.0
  webview_flutter: ^2.0.10
  system_settings: ^2.0.0
  intl: ^0.17.0
  ticket_material: ^0.3.1
  qr_flutter: ^4.0.0
  async: ^2.6.1
  http_parser: ^4.0.0
  cloudinary_sdk: ^3.0.1+7
  multi_select_flutter: ^4.0.0
  shared_preferences: ^2.0.7
  unique_list: ^1.0.1
  firebase_messaging: ^12.0.1
  flutter_local_notifications: ^9.0.0
  google_sign_in: ^5.2.1
  simple_fontellico_progress_dialog: ^0.2.0
  shimmer: ^2.0.0
  date_time_picker: ^2.1.0
  firebase_auth: ^3.6.2
  url_launcher: ^6.0.12
  flutter_launch: ^0.3.0
  money_converter: ^2.0.1
  google_fonts: ^2.1.0
  introduction_screen: ^2.1.0
  intro_views_flutter: ^3.2.0
  http_client: ^1.5.1
  google_maps_flutter: ^2.1.0
  flutter_plugin_android_lifecycle: ^2.0.4
  google_maps_flutter_platform_interface: ^2.1.3
  collection: ^1.15.0
  meta: ^1.7.0
  plugin_platform_interface: ^2.0.2
  stream_transform: ^2.0.0
  geolocator: ^7.7.1
  geocoding: ^2.0.1
  circular_profile_avatar: ^2.0.5
  rating_dialog: ^2.0.3
  simple_connection_checker: ^0.2.1
  share: ^2.0.4
  in_app_review: ^2.0.3
  auto_size_text: ^3.0.0
  flutter_easyloading: ^3.0.3
  google_api_headers: ^1.1.1
  google_maps_webservice: ^0.0.19
  rxdart: ^0.26.0
  flutter_google_places: ^0.3.0
  forex_conversion: ^0.0.3
  sign_in_with_apple: ^3.3.0
  another_flushbar: ^1.10.28
  screenshot: ^1.2.3
  image_gallery_saver: ^1.7.1
  permission_handler: ^8.3.0
  uuid: ^3.0.5
  html: ^0.15.0
  translator: ^0.1.7
  flutter_paypal: ^0.0.8
  http_auth: ^1.0.1
  new_version: ^0.3.0
  location: ^4.3.0
  persistent_bottom_nav_bar_v2: ^4.1.3
  flutter_keyboard_visibility: ^5.2.0
  day_picker: ^2.1.1
  awesome_stepper: ^0.1.3
  cool_stepper: ^1.2.1
  dots_indicator: ^2.1.0
  weather: ^2.0.1
  weather_icons: ^3.0.0
  expandable: ^5.0.1
  infinite_scroll: ^1.1.1
  infinite_scroll_pagination: ^3.2.0
  qr_code_scanner: ^1.0.0
  animated_splash_screen: ^1.2.0
  azlistview: ^2.0.0
  custom_refresh_indicator: ^1.2.1
  firebase_dynamic_links: ^4.3.3
  flutter_stripe: ^4.0.0
  
  
  
  
  

  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.2.4
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/vip.png"
  adaptive_icon_foreground: "assets/adaptive.png"
  adaptive_icon_background: "#FFFFFF"

flutter_native_splash:
  color: "#86A545"
  image: assets/logoc.png
  color_dark: "#86A545"
  android: true
  ios: true
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/eee.png
    - assets/canyon.jpg
    - assets/tourist.png
    - assets/logoc.png
    - assets/guide.png
    - assets/lake.jpg
    - assets/empty.png
    - assets/bg.jpg
    - assets/user_placeholder.png
    - assets/logo.png
    - assets/logo2.jpeg
    - assets/autumn.jpg
    - assets/nodata.png
    - assets/nodatabro.png
    - assets/building.jpg
    - assets/cancel.png
    - assets/noNotif.png
    - assets/intro1.jpg
    - assets/tag1.png
    - assets/arab.png
    - assets/euro.jpg
    - assets/french.png
    - assets/german.png
    - assets/italian.png
    - assets/russian.png
    - assets/spanish.png
    - assets/thai.png
    - assets/turkish.png
    - assets/us.png
    - assets/pngver1.png
    - assets/pyramid.png
    - assets/twin.png
    - assets/dott.png
    - assets/favos.png
    - assets/uved.png
    - assets/qrcode.png
    - assets/noffer.png
    - assets/ccc.jpg
    - assets/rate.jpg
    - assets/empty-pana.png
    - assets/nodis.png
    - assets/zzz.png
    - assets/qqq.png
    - assets/exca.png
    - assets/bgimg.png
    - assets/newbg.jpg
    - assets/temp1.png
    - assets/newbghome.jpg
    - assets/emptylikes.png
    - assets/emptyTickets.png
    - assets/notours2.png
    - assets/emptyNotifs.png
    - assets/fram1.png
    - assets/fram2.png
    - assets/fram3.png
    - assets/whatsapp.png
    - assets/viber.png
    - assets/telegram.png
    - assets/newTourist.png
    - assets/newGuide.png
    - assets/noTicket.png
    - assets/uploadPhoto.png
    - assets/splash.png
    - assets/city.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
